### ISSUE TITLE
'scanimage-tiff-reader' is not available from any of the selected providers

### ISSUE THREAD

**Issue by tbenst** [DavHau/pypi-crawlers#5]
This package is available on pypi here: https://pypi.org/project/scanimage-tiff-reader/

**Comment by DavHau** [comment]
I checked the json files of the dependency graph. There is only version 1.3 of scanimage-tiff-reader available. But not even this version is picked during build for some reason.

I need to check:
1. Why the crawler doesn't pick up the other wheel releases and no sdist releases at all
2. Why is the existing package not considered during dependency resolution.

Fixing this might also solve problems elsewhere. Thanks for the report!

**Comment by makefu** [comment]
@tbenst `nixpkgs-pytools` is all ears about your findings

**Comment by tbenst** [comment]
@makefu alas, I don't have any findings other than "hyphens in package names break things," just wanted to connect these two issues as progress on one -> progress on the other

**Comment by DavHau** [comment]
I just took a look into it. The problem here has nothing to do with hyphens or underscores. The crawler and mach-nix normalize all names. So this doesn't really matter.

The crawler actually picked up all wheel releases but they are windows only and therefore not usable.

For the sdist releases, the crawler crashes with the error:
```bash
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "setup.py", line 3, in <module>
    from wheel.bdist_wheel import bdist_wheel 
ModuleNotFoundError: No module named 'wheel'
```

The setup.py of scanimage-tiff-reader tries to import wheel but wheel is not available in the crawler environment.
In general missing modules are the most common issue for sdist packages failing to be analyzed.
I would consider all of these upstream issues, but still it might be a good idea to think about an improvement on our end since there are tons of libs importing stuff before installation.

I just checked the database of errors and the list of packages which needed to be installed to fix all of them is very very long.

If I pick only those packages where at least 500 releases on pypi require them, then I'm left with around 50 packages with a total closure size of 4GB. I will try to add those dependencies to the crawler soon. I might have to move the crawler to an instance with bigger disk.

**Comment by makefu** [comment]
Nice to hear you've found the issue.
For `python-package-init` we could think of querying the mach-nix dependency database and writing an expression directly for nixpkgs.
cheers

**Comment by DavHau** [comment]
Sure, go ahead! you can find all the data in [pypi-deps-db](https://github.com/DavHau/pypi-deps-db) (except the errors. Those are in a private postgres).
Some things to note:
 - both wheel and sdist json databases

**Comment by DavHau** [comment]
Sure, go ahead! you can find all the data in [pypi-deps-db](https://github.com/DavHau/pypi-deps-db) (except the errors. Those are in a private postgres).

Some things to note:
 - both wheel and sdist json databases use a custom compression format: sometimes a value can refer to other key which stores the actual information.
 - I made the mistake to not collect the `Requires-Python` attribute from the wheel metadata and instead rely on the correct naming of the files. But since the format of the filenames is not specified well enough, this is rather complicated and fails in general for wheels of type `none-any`. I'm planning to correct this here: https://github.com/DavHau/pypi-crawlers/issues/7
- When reading releases form the database, one must always consider the python version and the platform. Not all releases are compatible with all environments. Also dependency specification might have markers and therefore differ depending on your python version and system.

The logic of how to read this DB correctly is currently implemented in mach-nix in [providers.py](https://github.com/DavHau/mach-nix/blob/master/mach_nix/data/providers.py). It might be a good idea to move this logic directly to [pypi-deps-db](https://github.com/DavHau/pypi-deps-db). pypi-deps-db could become a python module which can be imported directly and has a nice api. Then we don't need to maintain this logic at multiple different places.

**Comment by DavHau** [comment]
I noticed that adding dependencies to the crawler doesn't solve the problem.
If i add for example `wheel` to make scanimage-tiff-reader working, the crawler will just ignore the fact that this package requires `wheel`. Later the build in mach-nix will fail because wheel will be missing since it is not stated as dependency of the package.

I think the best solution is to file a PR upstream and remove the use of wheel before setup() is called. This is a one line change.
also maybe ask the maintainer to release a wheel which is compatible with linux.

All packages which I would add to the crawler, I also have to add to mach-nix in general which will bloat the environments of all users. Not sure if this is the right way to go.

Currently it looks like the case with scanimage-tiff-reader is an exception and can easily be fixed upstream. if more of these kind of problems actually appear I will of course reconsider my point of view.

What do you think about it?

**Comment by makefu** [comment]
maybe you could also provide a "patch" file which extends the required buildinputs for a given package. Fixing upstream of course is always an option (however a bit less convenient).
Thanks for your investigations :+1:

**Comment by DavHau** [comment]
> maybe you could also provide a "patch" file which extends the required buildinputs for a given package. Fixing upstream of course is always an option (however a bit less convenient).

Yeah that could be done by providing a default set of overrides. I think i will add that soon, as more and more packages appear which need manual fixing.

BTW, The dependency graph now contains the requires_python attribute for all wheels. The pypi-deps-db should now be fully suitable as data source for your python tool.
